In [1]:

import torch
from nisrep.normalizing_flows.manager import *
import matplotlib.pyplot as plt
import numpy as np
torch.set_default_dtype(torch.double)

In [2]:
"""
def g(x):
    return torch.exp(-torch.sum(x**2,axis=-1)) #Vanilla Gaussian

def g(x): #ring, expect 0.51 in 2 dim
    q=torch.sqrt(torch.sum(x**2,axis=-1))
    #print(q)
    f=q.clone()
    a=torch.zeros_like(q)
    b=torch.ones_like(q)
    z=torch.where(q>0.45,a,q)
    #print(z)
    #print(torch.where(z>1,a,b))
    return torch.where(z<0.2,a,b)
"""

def g(x): #box: expect 16 in dim 2, 64 in dim 3
   
    q=torch.max(torch.abs(x),dim=-1).values
  
    a=torch.zeros_like(q)
    b=torch.ones_like(q)
   
    return torch.where(q>2,a,b)
"""
def tanp(x):
    return 100*(1+((torch.tan((x-0.5)*np.pi))**2))*np.pi   #derivative for jacobian

def gaussianp(x):
    mu=0
    sigma=1
    return torch.prod(-((x-mu)*torch.unsqueeze(torch.exp(-torch.sum((x-mu)**2/2*sigma**2,-1))/(np.sqrt(2*np.pi)*sigma**3),dim=-1)),-1)
"""
def normal(x,mu, sigma, n_flow):
    return (torch.exp(-torch.sum((x-mu)**2/(2*sigma**2),-1)))/(sigma*np.sqrt((2*np.pi)**n_flow))

n_flow=2
w = torch.empty((50000,n_flow)) 
torch.nn.init.uniform_(w)
v=100*torch.tan((w-0.5)*(np.pi))
print(v)
print("Value of the integral before mapping by CL")
print(torch.mean(torch.mul(g(v),torch.abs(torch.prod(tanp(w),axis=-1)))))
#print(torch.var(torch.mul(g(v),torch.prod(tanp(w),axis=-1))))

NF =  AffineManager(n_flow=n_flow)
NF.create_model(n_pass_through=1,n_cells=1, nn_width=2, NN=[20,20,20], roll_step=1)
#print(v)
v=NF.model(NF.format_input(v, dev=v.device))
jac=v[:,-1]
print(jac)
v=v[:,:n_flow]

mult=torch.mul(g(v),jac)

print("Value of the integral after mapping by CL")
print(torch.mean(torch.mul(mult,torch.prod(tanp(w),axis=-1))))


w = torch.empty((5000000,n_flow)) 
Z=torch.nn.init.normal_(w,std=1)

print("Value of the integral in gaussian")

print(torch.mean(g(Z)/(normal(Z,0,1,n_flow)))) 



tensor([[  90.1983,  462.9061],
        [  95.1634,  -47.9293],
        [-182.7555,  477.5595],
        ...,
        [  54.5957,   78.6481],
        [ -33.4138,  119.9316],
        [ 520.2395,  -60.5001]])
Value of the integral before mapping by CL
tensor(22.2136)
tensor([ 0.0224,  0.0224, -0.0129,  ...,  0.0224, -0.0129,  0.0224],
       grad_fn=<SelectBackward>)
Value of the integral after mapping by CL
tensor(9.1101, grad_fn=<MeanBackward0>)
Value of the integral in gaussian
tensor(16.0140)


In [3]:
def g(x): #box: expect 0.25 in dim2, 0,0039 in dim 8, 0,00195 in dim 9
   
    q=torch.max(torch.abs(x),dim=-1).values
  
    a=torch.zeros_like(q)
    b=torch.ones_like(q)
   
    return torch.where(q>0.5,a,b)

def gs(x): #box: expect 0.25 in dim2, 0,0039 in dim 8, 0,00195 in dim 9
   
    q=torch.max(torch.abs(x),dim=-1).values
    #s=torch.min(torch.abs(x),dim=-1).values
    a=torch.zeros_like(q)
    b=torch.ones_like(q)
    ret= torch.where(q>0.5,a,b)
    sret=torch.where((q>0.6)&(q<0.65),ret,5*b)
    return sret

def gaussian(x):
    return torch.exp( -((x[:,0]-0.5)**2+(x[:,1]-0.5)**2+(x[:,2]-0.5)**2+(x[:,3]-0.5)**2)/(0.05**2)) 

def gp(x):
    #s=100*gaussian(x)
    s=(1/((x[:,0]-0.5)**2+0.001**2))
    q=(1/((x[:,1])**2+0.001**2))
    t=100*torch.ones_like(x[:,0])
    return s+t+q
    
n_flow=2
w = torch.empty((250000,n_flow)) 
torch.nn.init.uniform_(w)

print("Value of the integral before mapping by CL")
print(torch.mean(gp(w)))
print("Value of the integral before mapping by CL minus constant")
print(torch.mean(gp(w)-100))
print("Variance")
print(torch.var(gp(w)))
print("SDEV")
print(torch.std(gp(w)))
print("Assumed error")
print(torch.std(gp(w))/np.sqrt(250000))
NF =  PWQuadManager(n_flow=n_flow)
NF.create_model(n_cells=2, n_bins=10, NN=[10,10,10], dev=torch.device("cpu"))
#print(v)
v=NF.model(NF.format_input(w,torch.device("cpu")))
jac=v[:,-1]
print(jac)
v=v[:,:n_flow]

mult=torch.mul(gp(v),jac)
print("Value of the integral after mapping by CL")
print(torch.mean(mult))
optim = torch.optim.Adamax(NF._model.parameters(),lr=1e-3, weight_decay=1e-5) 
res,err=NF._train_variance_forward_seq(gp,optim,"./logs/tmp/",10000,500,
                                           pretty_progressbar=True,save_best=True,run=None,dev=0,log=False,
                                               integrate=True,preburn_time=50)
print("Result")
print(res)
print(err)
#print(err/np.sqrt(500))
v=NF.best_model(NF.format_input(w,torch.device("cpu")))
jac=v[:,-1]
#print(jac)
v=v[:,:n_flow]
mult=torch.mul(gp(v),jac)
print("Loss reduction")
print(NF.best_loss/NF.int_loss)
print("Variance reduction")
print(torch.var(mult)/torch.var(gp(w)))
print("Value of the integral after mapping by training")
print(torch.mean(mult))

Value of the integral before mapping by CL
tensor(4832.5034)
Value of the integral before mapping by CL minus constant
tensor(4732.5034)
Variance
tensor(2.3324e+09)
SDEV
tensor(48295.2130)
Assumed error
tensor(96.5904)
tensor([1.1683, 0.2377, 0.7982,  ..., 0.9241, 1.0581, 0.8502],
       grad_fn=<SelectBackward>)
Value of the integral after mapping by CL
tensor(4779.9528, grad_fn=<MeanBackward0>)


tensor(4748.2377)
tensor(168.8080)
Result
4755.837743784804
100.9884531930085
Loss reduction
tensor(0.5670, grad_fn=<DivBackward0>)
Variance reduction
tensor(1.1105, grad_fn=<DivBackward0>)
Value of the integral after mapping by training
tensor(4824.5630, grad_fn=<MeanBackward0>)


In [4]:
n_flow=2
w = torch.empty((1000,n_flow)) 
torch.nn.init.uniform_(w)
maxim=torch.max(normal(w,0,1,n_flow))
i=0
res=0
q=0
while(i<5000):
    q=q+1
    w = torch.empty((1,n_flow)) 
    torch.nn.init.uniform_(w)
    w2=torch.empty((1,1))
    inter=normal(w,0,1,n_flow)
    if(inter/maxim>w2):
        res+=inter
        i=i+1
    if(i%1000==0):
        print(i)
print((res/5000)*5000/q)

print("Value of the integral before mapping by CL")
print(torch.mean(normal(w,0,1,n_flow)))

1000
2000
3000
3000
3000
4000
5000
tensor([0.0924])
Value of the integral before mapping by CL
tensor(0.1345)


In [3]:
w = torch.empty((120000,1)) 
torch.nn.init.uniform_(w)
z=torch.mean(1+torch.cos((w-0.5)*np.pi)**2)*np.pi#*16*(1.6)**4
print(1+torch.cos((w-0.5)*np.pi)**2)
print(z)

tensor([[1.1267],
        [1.7229],
        [1.4604],
        ...,
        [1.6648],
        [1.7874],
        [1.9973]])
tensor(4.7065)
